#ibmcloud-object-storage-plugin deployment
{{- $ns := include "ibm-object-storage-plugin.namespace" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ibm-object-storage-plugin.name" . }}
  namespace: {{ template "ibm-object-storage-plugin.namespace" . }}
  labels:
    app: {{ template "ibm-object-storage-plugin.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "ibm-object-storage-plugin.name" . }}
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ibm-object-storage-plugin.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "ibm-object-storage-plugin.name" . }}
        app.kubernetes.io/name: {{ template "ibm-object-storage-plugin.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        productID: "IBMCloudObjectStoragePlugin_{{ .Chart.AppVersion }}_Apache02_00000"
        productName: "ibmcloud-object-storage-plugin"
        productVersion: "{{ .Chart.AppVersion }}"
        autoUpdate: {{ randAlphaNum 5 | quote }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      tolerations:
      - operator: "Exists"
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: ibmcloud-object-storage-plugin
      {{- if or (contains "default" $ns) (contains "kube-system" $ns) }}
      securityContext:
        runAsUser: 2121
        fsGroup: 2121
      {{- end }}
      containers:
        - name: {{ template "ibm-object-storage-plugin.name" . }}-container
          {{- if contains "RHOCP" (.Values.provider | quote | upper) }}
          image: "{{ .Values.image.pluginImage.publicRegistry }}:{{ .Values.image.pluginBuild }}"
          {{- else }}
          image: "{{ .Values.image.pluginImage.ibmContainerRegistry }}:{{ .Values.image.pluginBuild }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resource.memory }}
              cpu: {{ .Values.resource.cpu }}
            limits:
              memory: {{ .Values.resource.memory }}
              cpu: {{ .Values.resource.cpu }}
          securityContext:
            capabilities:
              drop: ["ALL"]
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            {{- if or (contains "default" $ns) (contains "kube-system" $ns) }}
            runAsUser: 2121
            {{- end }}
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - ps aux | grep "provisioner=ibm.io/ibmc-s3fs" | grep -v grep > /dev/null
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 1
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - ps aux | grep "provisioner=ibm.io/ibmc-s3fs" | grep -v grep > /dev/null
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 1
          args:
            - "-provisioner=ibm.io/ibmc-s3fs"
          env:
          - name: DEBUG_TRACE
            value: 'false'
