{{- if .Values.build.enabled }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "nodejs.name" . }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "nodejs.imageName" . }}
  source:
    type: Git
    git:
      uri: {{ .Values.build.uri }}
      ref: {{ .Values.build.ref }}
{{- if .Values.build.contextDir }}
    contextDir: {{ .Values.build.contextDir }}
{{- end }}
{{- if and .Values.build.native.useDefaultDockerfile (eq .Values.build.mode "native") }}
    dockerfile: |-
      FROM registry.redhat.io/ubi8/nodejs-12:latest
      USER root
      RUN groupadd -r node && useradd -r -g node node
      WORKDIR "/app"
      COPY package*.json ./
      RUN npm install
      COPY . /app
      ENV PORT 8080
      EXPOSE 8080
      USER node
      CMD ["npm", "start"]
{{- end }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.build.native.dockerfilePath }}
  {{- if .Values.build.pullSecret }}
      pullSecret:
        name: {{ .Values.build.pullSecret }}
  {{- end }}
  {{- if .Values.build.env }}
      env:
        {{- tpl (toYaml .Values.build.env) . | nindent 8 }}
  {{- end }}
{{- if .Values.build.resources }}
  resources:
    {{- toYaml .Values.build.resources | nindent 4 }}
{{- end }}
  triggers:
    - type: ConfigChange
{{- end }}
