{{- if .Values.build.enabled }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "nodejs.name" . }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.build.uri }}
      ref: {{ .Values.build.ref }}
{{- if .Values.build.contextDir }}
    contextDir: {{ .Values.build.contextDir }}
{{- end }}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: nodejs:12
  {{- if .Values.build.pullSecret }}
      pullSecret:
        name: {{ .Values.build.pullSecret }}
  {{- end }}
  {{- if .Values.build.env }}
      env:
        {{- tpl (toYaml .Values.build.env) . | nindent 8 }}
  {{- end }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "nodejs.imageName" . }}
{{- if .Values.build.resources }}
  resources:
    {{- toYaml .Values.build.resources | nindent 4 }}
{{- end }}
  triggers:
    - type: ConfigChange
{{- end }}
